packages:
  - apps/*

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "prisma": true
  "esbuild": true
  "bcryptjs": true
  "canvas": true
  "@oxlint/binding-darwin-arm64": true
  "@rolldown/binding-darwin-arm64": true
